name: Build MacOS

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:

jobs:
  build:
    runs-on: macOS-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download and install Libs
        env:
          GITHUB_TOKEN: ${{ secrets.ONES_IBIS_LIBS_TOKEN }}
          LIBS_REPO: ${{ secrets.ONES_IBIS_LIBS_REPO }}
        run: |
          cd lib
          gh release download --repo "$LIBS_REPO" 1.0
          ls -lh
          sh install-libs-lin.sh

      - name: Install clusterAdmin lib
        run: |
          cd clusterAdminLibrary
          mvn -B clean install -PmacOS -DskipTests

      - name: Package Application
        run:  |
          cd clusterAdminApplication
          mvn -B clean package -PmacOS -DskipTests

      - name: Upload build to artifacts
        uses: actions/upload-artifact@master 
        with:
          name: OneS_ClusterAdmin-macOS
          path: ${{ github.workspace }}/clusterAdminApplication/target/OneS_ClusterAdmin-*-macOS.jar