name: Build Windows

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download and install Libs
        env:
          GITHUB_TOKEN: ${{ secrets.ONES_IBIS_LIBS_TOKEN }}
          LIBS_REPO: ${{ secrets.ONES_IBIS_LIBS_REPO }}
        shell: cmd
        run: |
          cd lib
          gh release download --repo "%LIBS_REPO%" 1.0
          dir
          install-libs-win.bat

      - name: Install clusterAdmin lib
        shell: cmd
        run: |
          cd clusterAdminLibrary
          mvn -B clean install -Pwindows-x86_64

      - name: Package Application
        shell: cmd
        run:  |
          cd clusterAdminApplication
          mvn -B clean package -Pwindows-x86_64

      - name: Upload build to artifacts
        uses: actions/upload-artifact@master 
        with:
          name: OneS_ClusterAdmin-windows-x64
          path: ${{ github.workspace }}\clusterAdminApplication\target\OneS_ClusterAdmin-*-windows-x64.jar